### ISSUE TITLE
Unconfirmed issue with media queries and iOS orientation switching

### ISSUE THREAD

**Issue by zachleat** [zachleat/BigText#9]
https://twitter.com/#!/philiprenich/status/102073401082003456
https://twitter.com/#!/philiprenich/status/102080134017851393

**Comment by zachleat** [comment]
Working with 0.1.7 on http://zachleat.github.io/BigText/demo/simpleDemo.html

Also make sure you’re using 

```css
html {
    -moz-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
```
